const constants = {
  ADD_BEER: "ADD_BEER",
  CLEAR_BEERS: "CLEAR_BEERS",
  SET_BEER_LIST: "SET_BEER_LIST",
  SET_SELECTED_BEER: "SET_SELECTED_BEER",
  SET_SELECTED_BREWERY: "SET_SELECTED_BREWERY"
}

export default constants;
