const constants = {
  ADD_BEER: "ADD_BEER",
  CLEAR_BEERS: "CLEAR_BEERS",
  SET_BEER_LIST: "SET_BEER_LIST",
  SET_SELECTED_BEER: "SET_SELECTED_BEER",
  SET_SELECTED_BREWERY: "SET_SELECTED_BREWERY",
  SET_BEER_SEARCH_TERM: "SET_BEER_SEARCH_TERM",
  SET_USER_INFO: "SET_USER_INFO"
}

export default constants;
